<?php

namespace Container0sqk7hB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_DoctrineMongodb_Odm_Command_EncryptionDumpFieldsMap_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.doctrine_mongodb.odm.command.encryption_dump_fields_map.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.doctrine_mongodb.odm.command.encryption_dump_fields_map.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('doctrine:mongodb:encryption:dump-fields-map', [], 'Dumps the encrypted fields map for all documents in the configured connections.', false, #[\Closure(name: 'doctrine_mongodb.odm.command.encryption_dump_fields_map', class: 'Doctrine\\Bundle\\MongoDBBundle\\Command\\Encryption\\DumpFieldsMapCommand')] fn (): \Doctrine\Bundle\MongoDBBundle\Command\Encryption\DumpFieldsMapCommand => ($container->privates['doctrine_mongodb.odm.command.encryption_dump_fields_map'] ?? $container->load('getDoctrineMongodb_Odm_Command_EncryptionDumpFieldsMapService')));
    }
}
