<?php

namespace Container0sqk7hB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_DefaultConnectionDiagnosticService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_mongodb.odm.default_connection_diagnostic' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\DataCollector\ConnectionDiagnostic
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/mongodb-odm-bundle/src/DataCollector/ConnectionDiagnostic.php';

        return $container->privates['doctrine_mongodb.odm.default_connection_diagnostic'] = new \Doctrine\Bundle\MongoDBBundle\DataCollector\ConnectionDiagnostic(($container->services['doctrine_mongodb.odm.default_connection'] ?? $container->load('getDoctrineMongodb_Odm_DefaultConnectionService')), ['typeMap' => ['root' => 'array', 'document' => 'array'], 'driver' => ['name' => 'symfony-mongodb', 'version' => '2.16.1']]);
    }
}
