<?php

namespace Container0sqk7hB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_Command_EncryptionDiagnosticService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_mongodb.odm.command.encryption_diagnostic' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\Encryption\DiagnosticCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/mongodb-odm-bundle/src/Command/Encryption/DiagnosticCommand.php';

        $container->privates['doctrine_mongodb.odm.command.encryption_diagnostic'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\Encryption\DiagnosticCommand(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'default' => ['privates', 'doctrine_mongodb.odm.default_connection_diagnostic', 'getDoctrineMongodb_Odm_DefaultConnectionDiagnosticService', true],
        ], [
            'default' => 'Doctrine\\Bundle\\MongoDBBundle\\DataCollector\\ConnectionDiagnostic',
        ]));

        $instance->setName('doctrine:mongodb:encryption:diagnostic');
        $instance->setDescription('Diagnose MongoDB configuration and server capabilities for each connection.');

        return $instance;
    }
}
