<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0sqk7hB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0sqk7hB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0sqk7hB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0sqk7hB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0sqk7hB\App_KernelDevDebugContainer([
    'container.build_hash' => '0sqk7hB',
    'container.build_id' => '576731cc',
    'container.build_time' => 1778156322,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0sqk7hB');
