<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXv1JtFG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXv1JtFG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXv1JtFG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXv1JtFG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXv1JtFG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xv1JtFG',
    'container.build_id' => '7287d787',
    'container.build_time' => 1778700704,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXv1JtFG');
